// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "084803ddf3b5c78682c56c2d92a58c1f4608f26da21e60b6bb28043fbcb3eff8")
