// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "2f4061909e8dc012ed6c512dc5bddc6a9151c2c93c0d66ddb9ca43acfaf316ee")
